# Generated by Django 4.2.7 on 2025-07-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='active', max_length=50),
        ),
    ]
